'use strict';
(() => {
 const root=document.documentElement;
 const media=matchMedia('(prefers-reduced-motion: reduce)');
 let paused=media.matches;
 const updateMotion=()=>{root.classList.toggle('motion-off',paused);root.classList.toggle('js-motion',!paused);document.querySelectorAll('.motion-control').forEach(b=>{b.textContent=paused?'Enable motion':'Pause motion';b.setAttribute('aria-pressed',String(paused));});window.dispatchEvent(new Event('motionchange'));};
 window.motionPaused=()=>paused;
 document.querySelectorAll('.motion-control').forEach(b=>b.addEventListener('click',()=>{paused=!paused;updateMotion();}));media.addEventListener('change',e=>{paused=e.matches;updateMotion();});updateMotion();
 const obs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-in');obs.unobserve(e.target);}}),{threshold:.12});document.querySelectorAll('.flow-reveal').forEach(el=>obs.observe(el));
 const words=[...document.querySelectorAll('.word-ink')];words.forEach(el=>{const copy=el.textContent.trim();el.setAttribute('aria-label',copy);el.textContent='';copy.split(/\s+/).forEach(w=>{const s=document.createElement('span');s.textContent=w+' ';s.setAttribute('aria-hidden','true');el.append(s);});});
 let queued=false;
 const onScroll=()=>{queued=false;const vh=innerHeight;const max=document.documentElement.scrollHeight-vh;document.querySelector('.progress-line')?.style.setProperty('transform',`scaleX(${max?scrollY/max:0})`);words.forEach(el=>{const box=el.getBoundingClientRect();const p=Math.max(0,Math.min(1,(vh*.87-box.top)/(vh*.6)));[...el.children].forEach((s,i)=>s.classList.toggle('lit',paused||p>i/el.children.length));});};
 addEventListener('scroll',()=>{if(!queued){queued=true;requestAnimationFrame(onScroll);}},{passive:true});addEventListener('resize',onScroll);onScroll();
 document.querySelector('.menu-toggle')?.addEventListener('click',e=>{const nav=document.querySelector('.nav-links');const open=nav.classList.toggle('is-open');e.currentTarget.setAttribute('aria-expanded',String(open));});
 document.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',()=>{document.querySelector('.nav-links').classList.remove('is-open');document.querySelector('.menu-toggle')?.setAttribute('aria-expanded','false');}));
 addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelector('.nav-links')?.classList.remove('is-open');document.querySelector('.menu-toggle')?.setAttribute('aria-expanded','false');}});
 document.querySelectorAll('.lookup').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();const q=form.querySelector('input').value.trim();const output=form.querySelector('.results');output.replaceChildren();const say=t=>{const p=document.createElement('p');p.className='result-message';p.textContent=t;output.append(p);};if(!/^\d{5}$/.test(q)){say('Enter a five-digit Malaysian postcode, for example 06050.');return;}const data=window.SEAT_INDEX;if(!data){say('The Seat index could not load. Open the full map below to look up your Seat.');return;}const codes=data.postcodes[q]||[];if(!codes.length){say(`No verified match for ${q} in this snapshot. A missing result does not mean you have no Seat. Try the full map below.`);return;}say(codes.length===1?'One possible Seat. Confirm the exact boundary on the map.':`${codes.length} possible Seats. This postcode crosses Seat boundaries.`);codes.forEach(code=>{const seat=data.seats[code];const a=document.createElement('a');a.className='result-link';a.href=`https://politikku.my/app/#parlimen/parti/${encodeURIComponent(code)}`;const name=document.createElement('span');name.textContent=seat.name;const state=document.createElement('small');state.textContent=code+' · '+seat.state;name.append(state);const arrow=document.createElement('span');arrow.textContent='↗';arrow.setAttribute('aria-hidden','true');a.append(name,arrow);output.append(a);});}));
})();
